# Generated by Django 4.2.2 on 2023-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_kod_course_code_rename_ime_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pass', 'Pass')], default='Fail', max_length=4),
        ),
    ]
