# Generated by Django 4.2.2 on 2023-07-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=128)),
                ('content', models.CharField(default='', max_length=9999)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
