# Generated by Django 4.2.2 on 2023-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_telephone_number_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='elective',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=30),
        ),
    ]
