# Generated by Django 4.2.2 on 2023-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_course_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pass', 'Pass')], default='Fail', max_length=30),
        ),
    ]
