# Generated by Django 4.2.2 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_post_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pass', 'Pass'), ('Dropped', 'Dropped')], default='Fail', max_length=30),
        ),
    ]
