# Generated by Django 4.2.2 on 2023-08-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_enrollment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
