# Generated by Django 4.2.2 on 2023-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(default='', max_length=128),
        ),
    ]
