# Generated by Django 4.2.2 on 2023-08-16 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
