# Generated by Django 4.2.2 on 2023-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enroll_times',
            field=models.IntegerField(default=1),
        ),
    ]
