# Generated by Django 4.2.2 on 2023-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_enrollment_enroll_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='initials',
            field=models.CharField(default='', max_length=128),
        ),
    ]
